sit_utilisateurs:
    path:     /Utilisateurs
    defaults: { _controller: SITUserBundle:utilisateur:utilisateurs }
sit_ajouter_utilisateur:
    path:     /ajouterUtilisateur/
    defaults:
        _controller: SITUserBundle:utilisateur:ajouterUtilisateur
sit_modifier_utilisateur:
    path:     /{idutilisateur}/modifierUtilisateur
    defaults:
        _controller: SITUserBundle:utilisateur:modifierUtilisateur
    requirements:
        idutilisateur: \d+

sit_supprimer_utilisateur:
    path:     /{idutilisateur}/supprimerUtilisateur
    defaults:
        _controller: SITUserBundle:utilisateur:supprimerUtilisateur
    requirements:
        idutilisateur: \d+