<?php

namespace SIT\PlatformBundle\Repository;

/**
 * etatProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class etatProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
