<?php

namespace SIT\PlatformBundle\Repository;

/**
 * noteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
}
