<?php

namespace SIT\PlatformBundle\Repository;

/**
 * noteAFaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class noteAFaireRepository extends \Doctrine\ORM\EntityRepository
{
}
