<?php

namespace SIT\PlatformBundle\Repository;

/**
 * societeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class societeRepository extends \Doctrine\ORM\EntityRepository
{
}
